spring:
  application:
    name: discodeit

  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  aop:
    proxy-target-class: true

logging:
  level:
    root: debug
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.security: warn
    org.springframework.web: warn

server:
  port: 8080
